services:
  server:
    container_name: myapp-backend
    image: ghcr.io/vukiman1/myapp-backend:latest
    restart: always
    env_file: ./.env.production
    volumes:
      - ./uploads:/app/uploads
    networks:
      - cloudflared
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

networks:
  cloudflared:
    external: true
